on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run unit tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: |
          npm install
          npm install -g vsce
          npm run test
  publish:
    needs: test
    name: Publish to VSCode Marketplace
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Build the front-end
        run: |
          cd front-end
          npm install
          npm i @angular/cli@16.2.12 -g
          ng build

      - name: Build the extension
        run: |
          npm install
          npm install -g vsce
          vsce package

      - name: Publish to marketplace
        run: vsce publish -p ${{ secrets.MARKETPLACE_SECRET }}
